import { launch } from '/home/user/institute--2-/tools/browser.mjs';
const OUT='/tmp/claude-0/-home-user-institute--2-/4aae5723-f3fa-5aaa-8cbc-ebd9e16d8b73/scratchpad/shots';
const b = await launch({ proxy:false });
const ctx = await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true, deviceScaleFactor:2 });
const p = await ctx.newPage();
await p.goto('http://127.0.0.1:4420/partner/', { waitUntil:'networkidle' });
await p.evaluate(()=>document.querySelector('#ways').scrollIntoView());
await p.waitForTimeout(900);
await p.evaluate(()=>{ document.addEventListener('click',e=>e.preventDefault(),true); });
await p.evaluate(()=>document.querySelectorAll('.door')[1].click());
await p.evaluate(()=>document.activeElement.blur());
await p.waitForTimeout(900);
await p.screenshot({path:`${OUT}/m-receipt-crop.png`, clip:{x:0,y:640,width:390,height:80}});
await b.close();
