import { launch } from '/home/user/institute--2-/tools/browser.mjs';
const OUT='/tmp/claude-0/-home-user-institute--2-/4aae5723-f3fa-5aaa-8cbc-ebd9e16d8b73/scratchpad/shots';
const b = await launch({ proxy:false });
const d = await b.newContext({ viewport:{width:1440,height:900}, deviceScaleFactor:3 });
const p = await d.newPage();
await p.goto('http://127.0.0.1:4410/pilots/', {waitUntil:'networkidle'});
await p.evaluate(()=>window.scrollTo(0,1400)); await p.waitForTimeout(1400);
console.log('inverted?', await p.evaluate(()=>document.querySelector('.nav').classList.contains('is-inverted')));
await p.screenshot({path:`${OUT}/pair-navy.png`, clip:{x:1140,y:0,width:300,height:70}});
const q = await d.newPage();
await q.goto('http://127.0.0.1:4410/', {waitUntil:'networkidle'});
const y = await q.evaluate(()=>{const e=document.querySelector('.on-cream');const r=e.getBoundingClientRect();return r.top+window.scrollY;});
await q.evaluate(y=>window.scrollTo(0,y+300), y); await q.waitForTimeout(1600);
console.log('inverted?', await q.evaluate(()=>document.querySelector('.nav').classList.contains('is-inverted')));
await q.screenshot({path:`${OUT}/pair-cream.png`, clip:{x:1140,y:0,width:300,height:70}});
await b.close();
