import { launch } from '/home/user/institute--2-/tools/browser.mjs';
const S='/tmp/claude-0/-home-user-institute--2-/4aae5723-f3fa-5aaa-8cbc-ebd9e16d8b73/scratchpad/';
const b=await launch({proxy:false});
const p=await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await p.goto('http://127.0.0.1:4420/partner/',{waitUntil:'networkidle'});
await p.screenshot({path:S+'cta-here.png',clip:{x:1100,y:0,width:340,height:70}});
const c2=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2,reducedMotion:'reduce'});
const p2=await c2.newPage(); await p2.goto('http://127.0.0.1:4420/',{waitUntil:'networkidle'});
await p2.click('[data-burger]'); await p2.waitForTimeout(60);
const st=await p2.evaluate(()=>{const m=document.querySelector('.menu');const a=m.querySelector('.menu__links a');
 return {menuOp:getComputedStyle(m).opacity,rowOp:getComputedStyle(a).opacity,label:document.querySelector('[data-burger-label]').textContent};});
console.log('REDUCE@60ms',JSON.stringify(st));
await p2.screenshot({path:S+'reduce.png',clip:{x:0,y:0,width:390,height:80}});
await b.close();
