import { launch } from '/home/user/institute--2-/tools/browser.mjs';
const b=await launch({proxy:false});
const ctx=await b.newContext({viewport:{width:1440,height:900}});
const pg=await ctx.newPage();
await pg.goto('http://127.0.0.1:4420/pilots/',{waitUntil:'networkidle'});
await pg.evaluate(async()=>{const H=document.body.scrollHeight;for(let y=0;y<H;y+=300){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,120));}});
await pg.waitForTimeout(1500);
const r=await pg.evaluate(()=>[...document.querySelectorAll('.pd')].map(s=>[...s.querySelectorAll('.pd__dl > div')].map(d=>getComputedStyle(d).opacity)));
console.log(JSON.stringify(r));
await b.close();
