import { launch } from '/home/user/institute--2-/tools/browser.mjs';
const OUT='/tmp/claude-0/-home-user-institute--2-/4aae5723-f3fa-5aaa-8cbc-ebd9e16d8b73/scratchpad/shots';
const b=await launch({proxy:false});
const ctx=await b.newContext({viewport:{width:1440,height:900},deviceScaleFactor:3});
const p=await ctx.newPage();
await p.goto('http://127.0.0.1:4454/pilots/',{waitUntil:'networkidle'}); await p.waitForTimeout(1000);
await p.evaluate(()=>window.scrollTo(0,1200)); await p.waitForTimeout(1400);
await p.screenshot({path:`${OUT}/z3-pilots-wide.png`,clip:{x:1180,y:0,width:260,height:70}});
const info=await p.evaluate(()=>{
  const out={};
  const el=document.querySelector('.nav__link.is-active');
  const cta=document.querySelector('.cta');
  const nav=document.querySelector('.nav');
  out.navH=getComputedStyle(nav).height;
  out.navRect=nav.getBoundingClientRect().toJSON();
  out.activeRect=el?el.getBoundingClientRect().toJSON():null;
  out.ctaRect=cta.getBoundingClientRect().toJSON();
  out.ctaAfter=getComputedStyle(cta,'::after').cssText||JSON.stringify({bg:getComputedStyle(cta,'::after').backgroundColor,h:getComputedStyle(cta,'::after').height,w:getComputedStyle(cta,'::after').width,t:getComputedStyle(cta,'::after').transform,op:getComputedStyle(cta,'::after').opacity,bottom:getComputedStyle(cta,'::after').bottom});
  out.activeAfter=el?JSON.stringify({bg:getComputedStyle(el,'::after').backgroundColor,h:getComputedStyle(el,'::after').height,t:getComputedStyle(el,'::after').transform,op:getComputedStyle(el,'::after').opacity,bottom:getComputedStyle(el,'::after').bottom}):null;
  const mark=document.querySelector('.nav__mark');
  out.markRect=mark.getBoundingClientRect().toJSON();
  const links=[...document.querySelectorAll('.nav__link')].map(a=>({t:a.textContent,r:a.getBoundingClientRect().toJSON(),fs:getComputedStyle(a).fontSize,ls:getComputedStyle(a).letterSpacing,fw:getComputedStyle(a).fontWeight,c:getComputedStyle(a).color}));
  out.links=links;
  out.ctaStyle={fs:getComputedStyle(cta).fontSize,ls:getComputedStyle(cta).letterSpacing,fw:getComputedStyle(cta).fontWeight,c:getComputedStyle(cta).color};
  out.gutter=getComputedStyle(document.documentElement).getPropertyValue('--gutter');
  out.max=getComputedStyle(document.documentElement).getPropertyValue('--max');
  return out;
});
console.log(JSON.stringify(info,null,1));
await b.close();
